# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  deploy-it:
    docker:
      - image: cimg/base:stable
    steps:
      - add_ssh_keys
      - checkout
      - run: sudo apt update
      - run: sudo apt install rsync
      - run:
          name: "Deploy to wyrtki"
          command: |
           echo 'wyrtki.soest.hawaii.edu ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBAJJyf1/zR4Lt5IA/+dY1VIqBHi5ZUx9/PYIYiHEW6b8rZBnR7gu7U7iqJiBn3Ob9m3YpQgqZD47zaaaHQ/Ykkc=' >> ~/.ssh/known_hosts
           rsync -va  assets graphs layouts dash-apps-env.yml flooding_days_app.py gunicorn_config.py.example piflooding.service.example uhslc-dash@wyrtki.soest.hawaii.edu:/srv/apps/pi-flooding 
      - run:
          name: "restart service on wyrtki"
          command: |
           ssh uhslc-dash@wyrtki.soest.hawaii.edu 'kill `grep "Starting gunicorn" /srv/apps/pi-flooding/error_log | tail -1 | cut -d\[ -f3 | cut -d\] -f`'


# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  deploy-it-workflow:
    jobs:
      - deploy-it:
          filters: 
            branches:
              only:
                - main

